# gitmsyncd — multi-provider Git sync engine
# Same image for all instances — configure via env vars at runtime
#
# Build:
#   podman build -t gitmsyncd:0.3.0 .
#
# Run (standalone):
#   podman run -d --name gitmsyncd -p 9097:9097 \
#     -e GITMSYNCD_DSN='dbi:Pg:dbname=gitmsyncd;host=db.example.com;port=5432' \
#     -e GITMSYNCD_DB_USER=gitmsyncd \
#     -e GITMSYNCD_DB_PASS=changeme \
#     -v gitmsyncd-workdir:/var/lib/gitmsyncd/workdir \
#     gitmsyncd:0.3.0
#
# Or use the compose file generated by Fleet.

FROM docker.io/library/rockylinux:9

# Install system packages — NEVER pip install
# perl-Mojolicious is in EPEL; enable it first
RUN dnf install -y --nodocs epel-release \
    && dnf install -y --nodocs \
    perl perl-Mojolicious perl-DBI perl-DBD-Pg \
    perl-Digest-SHA perl-POSIX perl-Getopt-Long \
    perl-File-Path perl-Sys-Hostname \
    git-core procps-ng \
    && dnf clean all

# Application layout
RUN mkdir -p /opt/gitmsyncd/{bin,lib/Gitmsyncd,web/templates,web/public,db} \
    && mkdir -p /var/lib/gitmsyncd/workdir \
    && useradd -r -d /opt/gitmsyncd -s /sbin/nologin gitmsyncd

# Copy application files
COPY cpanfile /opt/gitmsyncd/
COPY bin/gitmsyncd.pl bin/gitmsyncd-worker.pl /opt/gitmsyncd/bin/
COPY lib/Gitmsyncd/App.pm lib/Gitmsyncd/SyncEngine.pm lib/Gitmsyncd/ResourceGovernor.pm /opt/gitmsyncd/lib/Gitmsyncd/
COPY web/templates/*.html.ep /opt/gitmsyncd/web/templates/
COPY db/schema.sql /opt/gitmsyncd/db/

RUN chmod +x /opt/gitmsyncd/bin/*.pl \
    && chown -R gitmsyncd:gitmsyncd /var/lib/gitmsyncd

# Copy entrypoint that starts both web + worker
COPY packaging/container/entrypoint.sh /opt/gitmsyncd/entrypoint.sh
RUN chmod +x /opt/gitmsyncd/entrypoint.sh

WORKDIR /opt/gitmsyncd
USER gitmsyncd

# Default env — override at runtime
ENV GITMSYNCD_DSN=dbi:Pg:dbname=gitmsyncd;host=127.0.0.1;port=5432
ENV GITMSYNCD_DB_USER=gitmsyncd
ENV GITMSYNCD_DB_PASS=changeme
ENV GITMSYNCD_LISTEN=http://0.0.0.0:9097
ENV GITMSYNCD_WORKDIR=/var/lib/gitmsyncd/workdir
ENV GITMSYNCD_MAX_FORKS=4
ENV GITMSYNCD_MAX_LOAD=3.2
ENV GITMSYNCD_MIN_MEM_MB=256
ENV GITMSYNCD_MIN_DISK_MB=1024
ENV GITMSYNCD_WORKER_SET=default

EXPOSE 9097

ENTRYPOINT ["/opt/gitmsyncd/entrypoint.sh"]
